import { registerWidget } from 'netlify-cms-core/src';
import { NetlifyCmsWidgetString } from 'netlify-cms-widget-string/src';
import { NetlifyCmsWidgetNumber } from 'netlify-cms-widget-number/src';
import { NetlifyCmsWidgetText } from 'netlify-cms-widget-text/src';
import { NetlifyCmsWidgetImage } from 'netlify-cms-widget-image/src';
import { NetlifyCmsWidgetFile } from 'netlify-cms-widget-file/src';
import { NetlifyCmsWidgetDate } from 'netlify-cms-widget-date/src';
import { NetlifyCmsWidgetDatetime } from 'netlify-cms-widget-datetime/src';
import { NetlifyCmsWidgetSelect } from 'netlify-cms-widget-select/src';
import { NetlifyCmsWidgetMarkdown } from 'netlify-cms-widget-markdown/src';
import { NetlifyCmsWidgetList } from 'netlify-cms-widget-list/src';
import { NetlifyCmsWidgetObject } from 'netlify-cms-widget-object/src';
import { NetlifyCmsWidgetRelation } from 'netlify-cms-widget-relation/src';
import { NetlifyCmsWidgetBoolean } from 'netlify-cms-widget-boolean/src';
import { NetlifyCmsWidgetMap } from 'netlify-cms-widget-map/src';

registerWidget('string', NetlifyCmsWidgetString.Control, NetlifyCmsWidgetString.Preview);
registerWidget('number', NetlifyCmsWidgetNumber.Control, NetlifyCmsWidgetNumber.Preview);
registerWidget('text', NetlifyCmsWidgetText.Control, NetlifyCmsWidgetText.Preview);
registerWidget('list', NetlifyCmsWidgetList.Control, NetlifyCmsWidgetList.Preview);
registerWidget('markdown', NetlifyCmsWidgetMarkdown.Control, NetlifyCmsWidgetMarkdown.Preview);
registerWidget('image', NetlifyCmsWidgetImage.Control, NetlifyCmsWidgetImage.Preview);
registerWidget('file', NetlifyCmsWidgetFile.Control, NetlifyCmsWidgetFile.Preview);
registerWidget('date', NetlifyCmsWidgetDate.Control, NetlifyCmsWidgetDate.Preview);
registerWidget('datetime', NetlifyCmsWidgetDatetime.Control, NetlifyCmsWidgetDatetime.Preview);
registerWidget('select', NetlifyCmsWidgetSelect.Control, NetlifyCmsWidgetSelect.Preview);
registerWidget('object', NetlifyCmsWidgetObject.Control, NetlifyCmsWidgetObject.Preview);
registerWidget('relation', NetlifyCmsWidgetRelation.Control, NetlifyCmsWidgetRelation.Preview);
registerWidget('boolean', NetlifyCmsWidgetBoolean.Control);
registerWidget('map', NetlifyCmsWidgetMap.Control, NetlifyCmsWidgetMap.Preview);
