import { registerWidget } from 'netlify-cms-core/src';
import * as NetlifyCmsWidgetString from 'netlify-cms-widget-string/src';
import * as NetlifyCmsWidgetNumber from 'netlify-cms-widget-number/src';
import * as NetlifyCmsWidgetText from 'netlify-cms-widget-text/src';
import * as NetlifyCmsWidgetImage from 'netlify-cms-widget-image/src';
import * as NetlifyCmsWidgetFile from 'netlify-cms-widget-file/src';
import * as NetlifyCmsWidgetDate from 'netlify-cms-widget-date/src';
import * as NetlifyCmsWidgetDatetime from 'netlify-cms-widget-datetime/src';
import * as NetlifyCmsWidgetSelect from 'netlify-cms-widget-select/src';
import * as NetlifyCmsWidgetMarkdown from 'netlify-cms-widget-markdown/src';
import * as NetlifyCmsWidgetList from 'netlify-cms-widget-list/src';
import * as NetlifyCmsWidgetObject from 'netlify-cms-widget-object/src';
import * as NetlifyCmsWidgetRelation from 'netlify-cms-widget-relation/src';
import * as NetlifyCmsWidgetBoolean from 'netlify-cms-widget-boolean/src';
import * as NetlifyCmsWidgetMap from 'netlify-cms-widget-map/src';

registerWidget('string', NetlifyCmsWidgetString.Control, NetlifyCmsWidgetString.Preview);
registerWidget('number', NetlifyCmsWidgetNumber.Control, NetlifyCmsWidgetNumber.Preview);
registerWidget('text', NetlifyCmsWidgetText.Control, NetlifyCmsWidgetText.Preview);
registerWidget('list', NetlifyCmsWidgetList.Control, NetlifyCmsWidgetList.Preview);
registerWidget('markdown', NetlifyCmsWidgetMarkdown.Control, NetlifyCmsWidgetMarkdown.Preview);
registerWidget('image', NetlifyCmsWidgetImage.Control, NetlifyCmsWidgetImage.Preview);
registerWidget('file', NetlifyCmsWidgetFile.Control, NetlifyCmsWidgetFile.Preview);
registerWidget('date', NetlifyCmsWidgetDate.Control, NetlifyCmsWidgetDate.Preview);
registerWidget('datetime', NetlifyCmsWidgetDatetime.Control, NetlifyCmsWidgetDatetime.Preview);
registerWidget('select', NetlifyCmsWidgetSelect.Control, NetlifyCmsWidgetSelect.Preview);
registerWidget('object', NetlifyCmsWidgetObject.Control, NetlifyCmsWidgetObject.Preview);
registerWidget('relation', NetlifyCmsWidgetRelation.Control, NetlifyCmsWidgetRelation.Preview);
registerWidget('boolean', NetlifyCmsWidgetBoolean.Control);
registerWidget('map', NetlifyCmsWidgetMap.Control, NetlifyCmsWidgetMap.Preview);
