import { initial, last, partial, result, trim, trimStart } from 'lodash-es';

import {
  APIError,
  basename,
  branchFromContentKey,
  CMS_BRANCH_PREFIX,
  DEFAULT_PR_BODY,
  EditorialWorkflowError,
  generateContentKey,
  getAllResponses,
  isCMSLabel,
  labelToStatus,
  localForage,
  MERGE_COMMIT_MESSAGE,
  parseContentKey,
  readFileMetadata,
  requestWithBackoff,
  statusToLabel,
  unsentRequest,
} from '@/lib/util/index';

import type {
  ApiRequest,
  CmsAssetProxy,
  CmsDataFile,
  CmsPersistOptions,
  FetchError,
  Semaphore,
} from '@/lib/util/index';
import type {
  FilesResponse,
  ForgejoBranch,
  ForgejoChangedFile,
  ForgejoCompareResponse,
  ForgejoLabel,
  ForgejoPullRequest,
  ForgejoRepository,
  ForgejoUser,
  GitGetBlobResponse,
  GitGetTreeResponse,
  ReposListCommitsResponse,
} from './types';

export const API_NAME = 'Forgejo';

/** Sentinel PR number for a branch that is under editorial workflow but has no PR yet. */
export const MOCK_PULL_REQUEST = -1;

// Members are forwarded straight from `config.backend`, where an unset key
// reads as `undefined`; the constructor defaults each one.
export interface Config {
  apiRoot?: string | undefined;
  token?: string | undefined;
  branch?: string | undefined;
  repo?: string | undefined;
  originRepo?: string | undefined;
  cmsLabelPrefix?: string | undefined;
  initialWorkflowStatus?: string | undefined;
}

enum FileOperation {
  CREATE = 'create',
  DELETE = 'delete',
  UPDATE = 'update',
}

export interface ChangeFileOperation {
  content?: string;
  from_path?: string;
  path: string;
  operation: FileOperation;
  sha?: string;
}

interface MetaDataObjects {
  entry: { path: string, sha: string };
  files: MediaFile[];
}

export interface Metadata {
  type: string;
  objects: MetaDataObjects;
  branch: string;
  status: string;
  collection: string;
  commitMessage: string;
  version?: string;
  user: string;
  title?: string;
  description?: string;
  timeStamp: string;
}

export interface BlobArgs {
  sha: string;
  repoURL: string;
  parseText: boolean;
}

type Param = string | number | undefined;

export type Options = RequestInit & {
  params?: Record<string, Param | Record<string, Param> | string[]>,
};

type MediaFile = {
  sha: string,
  path: string,
};

export default class API {
  apiRoot: string;
  token: string;
  branch: string;
  repo: string;
  originRepo: string;
  repoOwner: string;
  repoName: string;
  originRepoOwner: string;
  originRepoName: string;
  repoURL: string;
  originRepoURL: string;
  cmsLabelPrefix: string;
  initialWorkflowStatus: string;

  _userPromise?: Promise<ForgejoUser>;
  _metadataSemaphore?: Semaphore;

  commitAuthor?: {};

  constructor(config: Config) {
    this.apiRoot = config.apiRoot || 'https://codeberg.org/api/v1';
    this.token = config.token || '';
    this.branch = config.branch || 'main';
    this.repo = config.repo || '';
    this.originRepo = config.originRepo || this.repo;
    this.cmsLabelPrefix = config.cmsLabelPrefix || '';
    this.initialWorkflowStatus = config.initialWorkflowStatus || 'draft';
    this.repoURL = `/repos/${this.repo}`;
    this.originRepoURL = `/repos/${this.originRepo}`;

    const [repoParts, originRepoParts] = [this.repo.split('/'), this.originRepo.split('/')];
    this.repoOwner = repoParts[0];
    this.repoName = repoParts[1];

    this.originRepoOwner = originRepoParts[0];
    this.originRepoName = originRepoParts[1];
  }

  static DEFAULT_COMMIT_MESSAGE = 'Automatically generated by Decap CMS';

  user(): Promise<{ full_name: string, login: string, email: string, avatar_url: string }> {
    if (!this._userPromise) {
      this._userPromise = this.getUser();
    }
    return this._userPromise;
  }

  getUser() {
    return this.request('/user') as Promise<ForgejoUser>;
  }

  async hasWriteAccess() {
    try {
      const result: ForgejoRepository = await this.request(this.repoURL);
      // update config repoOwner to avoid case sensitivity issues with Forgejo
      this.repoOwner = result.owner.login;
      return result.permissions.push;
    } catch (error: unknown) {
      console.error('Problem fetching repo data from Forgejo');
      throw error;
    }
  }

  reset() {
    // no op
  }

  requestHeaders(headers = {}) {
    const baseHeader: Record<string, string> = {
      'Content-Type': 'application/json; charset=utf-8',
      ...headers,
    };

    if (this.token) {
      baseHeader.Authorization = `token ${this.token}`;
      return Promise.resolve(baseHeader);
    }

    return Promise.resolve(baseHeader);
  }

  async parseJsonResponse(response: Response) {
    const json = await response.json();
    if (!response.ok) {
      return Promise.reject(json);
    }
    return json;
  }

  urlFor(path: string, options: Options) {
    const params = [];
    if (options.params) {
      for (const key in options.params) {
        params.push(`${key}=${encodeURIComponent(options.params[key] as string)}`);
      }
    }
    if (params.length) {
      path += `?${params.join('&')}`;
    }
    return this.apiRoot + path;
  }

  parseResponse(response: Response) {
    const contentType = response.headers.get('Content-Type');
    if (contentType && contentType.match(/json/)) {
      return this.parseJsonResponse(response);
    }
    const textPromise = response.text().then(text => {
      if (!response.ok) {
        return Promise.reject(text);
      }
      return text;
    });
    return textPromise;
  }

  handleRequestError(error: FetchError, responseStatus: number) {
    throw new APIError(error.message, responseStatus, API_NAME);
  }

  buildRequest(req: ApiRequest) {
    return req;
  }

  async request(
    path: string,
    options: Options = {},
    parser = (response: Response) => this.parseResponse(response),
  ) {
    options = { cache: 'no-cache', ...options };
    const headers = await this.requestHeaders(options.headers || {});
    const url = this.urlFor(path, options);
    let responseStatus = 500;

    try {
      const req = unsentRequest.fromFetchArguments(url, {
        ...options,
        headers,
      }) as unknown as ApiRequest;
      const response = await requestWithBackoff(this, req);
      responseStatus = response.status;
      const parsedResponse = await parser(response);
      return parsedResponse;
    } catch (error: unknown) {
      return this.handleRequestError(error as FetchError, responseStatus);
    }
  }

  nextUrlProcessor() {
    return (url: string) => url;
  }

  async requestAllPages<T>(url: string, options: Options = {}) {
    options = { cache: 'no-cache', ...options };
    const headers = await this.requestHeaders(options.headers || {});
    const processedURL = this.urlFor(url, options);
    const allResponses = await getAllResponses(
      processedURL,
      { ...options, headers },
      'next',
      this.nextUrlProcessor(),
    );
    const pages: T[][] = await Promise.all(
      allResponses.map((res: Response) => this.parseResponse(res)),
    );
    return ([] as T[]).concat(...pages);
  }

  generateContentKey(collectionName: string, slug: string) {
    return generateContentKey(collectionName, slug);
  }

  parseContentKey(contentKey: string) {
    return parseContentKey(contentKey);
  }

  async readFile(
    path: string,
    sha?: string | null,
    {
      branch = this.branch,
      repoURL = this.repoURL,
      parseText = true,
    }: {
      branch?: string,
      repoURL?: string,
      parseText?: boolean,
    } = {},
  ) {
    if (!sha) {
      sha = await this.getFileSha(path, { repoURL, branch });
    }
    const content = await this.fetchBlobContent({ sha: sha as string, repoURL, parseText });
    return content;
  }

  async readFileMetadata(path: string, sha: string | null | undefined) {
    const fetchFileMetadata = async () => {
      try {
        const result: ReposListCommitsResponse = await this.request(
          `${this.originRepoURL}/commits`,
          {
            params: { path, sha: this.branch, stat: 'false' },
          },
        );
        const { commit } = result[0];
        return {
          author: commit.author.name || commit.author.email,
          updatedOn: commit.author.date,
        };
      } catch (e: unknown) {
        return { author: '', updatedOn: '' };
      }
    };
    const fileMetadata = await readFileMetadata(sha, fetchFileMetadata, localForage);
    return fileMetadata;
  }

  async fetchBlobContent({ sha, repoURL, parseText }: BlobArgs) {
    const result: GitGetBlobResponse = await this.request(`${repoURL}/git/blobs/${sha}`, {
      cache: 'force-cache',
    });

    if (parseText) {
      // treat content as a utf-8 string
      const content = btoa(result.content);
      return content;
    } else {
      // treat content as binary and convert to blob
      const content = atob(result.content);
      const byteArray = new Uint8Array(content.length);
      for (let i = 0; i < content.length; i++) {
        byteArray[i] = content.charCodeAt(i);
      }
      const blob = new Blob([byteArray]);
      return blob;
    }
  }

  async listFiles(
    path: string,
    { repoURL = this.repoURL, branch = this.branch, depth = 1 } = {},
    folderSupport?: boolean,
  ): Promise<{ type: string, id: string, name: string, path: string, size: number }[]> {
    const folder = trim(path, '/');
    try {
      const result: GitGetTreeResponse = await this.request(
        `${repoURL}/git/trees/${branch}:${encodeURIComponent(folder)}`,
        {
          // Forgejo's API (Gitea-compatible) supports recursive=1 for getting
          // the entire recursive tree, or omitting it for the non-recursive tree.
          params: depth > 1 ? { recursive: 1 } : {},
        },
      );
      return (
        result.tree
          // filter only files and/or folders up to the required depth
          .filter(
            file =>
              (!folderSupport ? file.type === 'blob' : true)
              && decodeURIComponent(file.path).split('/').length <= depth,
          )
          .map(file => ({
            type: file.type,
            id: file.sha,
            name: basename(file.path),
            path: `${folder}/${file.path}`,
            size: file.size!,
          }))
      );
    } catch (err: unknown) {
      if (
        err
        && typeof err === 'object'
        && 'status' in err
        && (err as { status: number }).status === 404
      ) {
        console.info('[StaticCMS] This 404 was expected and handled appropriately.');
        return [];
      } else {
        throw err;
      }
    }
  }

  async persistFiles(
    dataFiles: CmsDataFile[],
    mediaFiles: CmsAssetProxy[],
    options: CmsPersistOptions,
  ) {
    const files: (CmsDataFile | CmsAssetProxy)[] = mediaFiles.concat(dataFiles as any);
    const operations = await this.getChangeFileOperations(files, this.branch);
    return this.changeFiles(operations, this.branch, options);
  }

  async changeFiles(operations: ChangeFileOperation[], branch: string, options: CmsPersistOptions) {
    return (await this.request(`${this.repoURL}/contents`, {
      method: 'POST',
      body: JSON.stringify({
        branch,
        files: operations,
        message: options.commitMessage,
      }),
    })) as FilesResponse;
  }

  async getChangeFileOperations(files: { path: string, newPath?: string | undefined }[], branch: string) {
    const items: ChangeFileOperation[] = await Promise.all(
      files.map(async file => {
        const content = await result(
          file,
          'toBase64',
          partial(this.toBase64, (file as CmsDataFile).raw),
        );
        let sha;
        let operation;
        let from_path;
        let path = trimStart(file.path, '/');
        try {
          sha = await this.getFileSha(file.path, { branch });
          operation = FileOperation.UPDATE;
          from_path = file.newPath && path;
          path = file.newPath ? trimStart(file.newPath, '/') : path;
        } catch {
          sha = undefined;
          operation = FileOperation.CREATE;
        }

        return {
          operation,
          content,
          path,
          from_path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    return items;
  }

  async getFileSha(path: string, { repoURL = this.repoURL, branch = this.branch } = {}) {
    /**
     * We need to request the tree first to get the SHA. We use extended SHA-1
     * syntax (<rev>:<path>) to get a blob from a tree without having to recurse
     * through the tree.
     */

    const pathArray = path.split('/');
    const filename = last(pathArray);
    const directory = initial(pathArray).join('/');
    const fileDataPath = encodeURIComponent(directory);
    const fileDataURL = `${repoURL}/git/trees/${branch}:${fileDataPath}`;

    const result: GitGetTreeResponse = await this.request(fileDataURL);
    const file = result.tree.find(file => file.path === filename);
    if (file) {
      return file.sha;
    } else {
      throw new APIError('Not Found', 404, API_NAME);
    }
  }

  async deleteFiles(paths: string[], message: string) {
    const operations: ChangeFileOperation[] = await Promise.all(
      paths.map(async path => {
        const sha = await this.getFileSha(path);

        return {
          operation: FileOperation.DELETE,
          path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    return this.changeFiles(operations, this.branch, { commitMessage: message });
  }

  toBase64(str: string) {
    return Promise.resolve(btoa(str));
  }

  // --- Editorial workflow (branches / pull requests / labels) ---
  //
  // Forgejo's REST API is Gitea-compatible: a "pull request" is backed by an
  // issue, and its labels double as the CMS workflow status (draft /
  // pending_review / pending_publish), the same mechanism the GitHub backend
  // uses. See CMS_BRANCH_PREFIX / statusToLabel / labelToStatus in
  // `@/lib/util`.

  async getBranch(branchName: string): Promise<ForgejoBranch> {
    return this.request(`${this.repoURL}/branches/${encodeURIComponent(branchName)}`);
  }

  async createBranch(branchName: string, oldBranchName: string = this.branch): Promise<ForgejoBranch> {
    return this.request(`${this.repoURL}/branches`, {
      method: 'POST',
      body: JSON.stringify({
        new_branch_name: branchName,
        old_ref_name: oldBranchName,
      }),
    });
  }

  async deleteBranch(branchName: string): Promise<void> {
    await this.request(`${this.repoURL}/branches/${encodeURIComponent(branchName)}`, {
      method: 'DELETE',
    });
  }

  async getPullRequests(
    state: 'open' | 'closed' | 'all' = 'open',
    head?: string,
  ): Promise<ForgejoPullRequest[]> {
    const pullRequests = await this.requestAllPages<ForgejoPullRequest>(
      `${this.originRepoURL}/pulls`,
      {
        params: { state, base: this.branch, limit: 100 },
      },
    );
    if (!head) {
      return pullRequests;
    }

    return pullRequests.filter(pr => {
      const label = pr.head?.label;
      const repoOwner = pr.head?.repo?.owner?.login;
      const ref = pr.head?.ref;

      if (label === head) {
        return true;
      }
      if (repoOwner && ref) {
        return `${repoOwner}:${ref}` === head;
      }

      // Forgejo may return a branch-only label (`cms/new-branch`, no owner)
      // for same-repository PRs, which then never matched and left new
      // editorial workflow entries out of the workflow board.
      if (ref) {
        return `${this.repoOwner}:${ref}` === head;
      }

      return false;
    });
  }

  async getHeadReference(head: string) {
    return `${this.repoOwner}:${head}`;
  }

  async getBranchPullRequest(branchName: string): Promise<ForgejoPullRequest> {
    const pullRequests = await this.getPullRequests('open', `${this.repoOwner}:${branchName}`);
    const cmsPullRequests = pullRequests.filter(pr => pr.labels.some(l => isCMSLabel(l.name, this.cmsLabelPrefix)));
    if (cmsPullRequests.length > 0) {
      return cmsPullRequests[0];
    }
    throw new EditorialWorkflowError('content is not under editorial workflow', true);
  }

  async createPR(
    title: string,
    head: string,
    body: string = DEFAULT_PR_BODY,
  ): Promise<ForgejoPullRequest> {
    return this.request(`${this.originRepoURL}/pulls`, {
      method: 'POST',
      body: JSON.stringify({
        title,
        head: await this.getHeadReference(head),
        base: this.branch,
        body,
      }),
    });
  }

  async updatePR(number: number, state: 'open' | 'closed'): Promise<ForgejoPullRequest> {
    return this.request(`${this.originRepoURL}/pulls/${number}`, {
      method: 'PATCH',
      body: JSON.stringify({ state }),
    });
  }

  async closePR(number: number): Promise<ForgejoPullRequest> {
    return this.updatePR(number, 'closed');
  }

  async mergePR(pullRequest: ForgejoPullRequest): Promise<void> {
    await this.request(`${this.originRepoURL}/pulls/${pullRequest.number}/merge`, {
      method: 'POST',
      body: JSON.stringify({
        Do: 'merge',
        MergeMessageField: MERGE_COMMIT_MESSAGE,
      }),
    });
  }

  async getPullRequestFiles(number: number): Promise<ForgejoChangedFile[]> {
    if (number === MOCK_PULL_REQUEST) {
      return [];
    }
    return this.request(`${this.originRepoURL}/pulls/${number}/files`);
  }

  async getDifferences(from: string, to: string): Promise<ForgejoCompareResponse> {
    return this.request(
      `${this.originRepoURL}/compare/${encodeURIComponent(from)}...${encodeURIComponent(to)}`,
    );
  }

  async updatePullRequestLabels(number: number, labels: number[]): Promise<ForgejoLabel[]> {
    return this.request(`${this.originRepoURL}/issues/${number}/labels`, {
      method: 'PUT',
      body: JSON.stringify({ labels }),
    });
  }

  async getLabels(): Promise<ForgejoLabel[]> {
    return this.requestAllPages<ForgejoLabel>(`${this.originRepoURL}/labels`, {
      params: { limit: 100 },
    });
  }

  async createLabel(name: string, color = '0052cc'): Promise<ForgejoLabel> {
    return this.request(`${this.originRepoURL}/labels`, {
      method: 'POST',
      body: JSON.stringify({ name, color }),
    });
  }

  async getOrCreateLabel(name: string): Promise<ForgejoLabel> {
    const labels = await this.getLabels();
    const existing = labels.find(l => l.name === name);
    if (existing) {
      return existing;
    }
    return this.createLabel(name);
  }

  async setPullRequestStatus(pullRequest: ForgejoPullRequest, status: string): Promise<void> {
    if (pullRequest.number === MOCK_PULL_REQUEST) {
      return;
    }

    const newLabel = statusToLabel(status, this.cmsLabelPrefix);

    // Get or create the new status label
    const label = await this.getOrCreateLabel(newLabel);

    if (typeof label.id !== 'number') {
      throw new Error(
        `Status label "${label.name}" returned from getOrCreateLabel is missing a numeric id`,
      );
    }

    // Get current labels and filter out old CMS labels and labels without ids
    const currentLabels = pullRequest.labels
      .filter(l => !isCMSLabel(l.name, this.cmsLabelPrefix))
      .filter(l => typeof l.id === 'number')
      .map(l => l.id as number);

    // Add the new status label
    await this.updatePullRequestLabels(pullRequest.number, [...currentLabels, label.id]);
  }

  async listUnpublishedBranches(): Promise<string[]> {
    const pullRequests = await this.getPullRequests('open');
    const cmsBranches = pullRequests
      .filter(
        pr =>
          pr.head.ref.startsWith(`${CMS_BRANCH_PREFIX}/`)
          && pr.labels.some(l => isCMSLabel(l.name, this.cmsLabelPrefix)),
      )
      .map(pr => pr.head.ref);

    return cmsBranches;
  }

  async retrieveUnpublishedEntryData(contentKey: string) {
    const branch = branchFromContentKey(contentKey);
    const pullRequest = await this.getBranchPullRequest(branch);

    let diffs: { path: string, newFile: boolean, id: string }[];
    try {
      const headRef = await this.getHeadReference(branch);
      const compareResult = await this.getDifferences(this.branch, headRef);
      diffs = compareResult.files.map(file => ({
        path: file.filename,
        newFile: file.status === 'added',
        id: file.sha || '',
      }));
    } catch (e: unknown) {
      const files = await this.getPullRequestFiles(pullRequest.number);
      diffs = files.map(file => ({
        path: file.filename,
        newFile: file.status === 'added',
        id: '',
      }));
    }

    const statusLabel = pullRequest.labels.find(l => isCMSLabel(l.name, this.cmsLabelPrefix));
    const status = statusLabel
      ? labelToStatus(statusLabel.name, this.cmsLabelPrefix)
      : this.initialWorkflowStatus;

    const { collection, slug } = this.parseContentKey(contentKey);

    return {
      collection,
      slug,
      status,
      diffs,
      updatedAt: pullRequest.updated_at || new Date().toISOString(),
      author: { name: pullRequest.user?.login || 'Unknown' },
    };
  }

  async updateUnpublishedEntryStatus(collection: string, slug: string, newStatus: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);
    const pullRequest = await this.getBranchPullRequest(branch);
    await this.setPullRequestStatus(pullRequest, newStatus);
  }

  async deleteUnpublishedEntry(collection: string, slug: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    try {
      const pullRequest = await this.getBranchPullRequest(branch);
      if (pullRequest.number !== MOCK_PULL_REQUEST) {
        await this.closePR(pullRequest.number);
      }
    } catch (e: unknown) {
      // Only ignore expected errors (e.g. no PR / not under editorial workflow).
      if (e instanceof EditorialWorkflowError || (e instanceof APIError && e.status === 404)) {
        // PR might not exist or entry is not under editorial workflow; continue to delete branch.
      } else {
        // Unexpected error: rethrow so we don't delete the branch in an unknown state.
        throw e;
      }
    }

    await this.deleteBranch(branch);
  }

  async publishUnpublishedEntry(collection: string, slug: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    const pullRequest = await this.getBranchPullRequest(branch);
    if (pullRequest.number === MOCK_PULL_REQUEST) {
      throw new APIError('Cannot publish entry without a pull request', 400, API_NAME);
    }
    await this.mergePR(pullRequest);
    await this.deleteBranch(branch);
  }

  async editorialWorkflowGit(
    files: (CmsDataFile | CmsAssetProxy)[],
    slug: string,
    collection: string,
    options: CmsPersistOptions,
  ) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    let branchExists = false;
    try {
      await this.getBranch(branch);
      branchExists = true;
    } catch (e: unknown) {
      // Only treat a 404 "not found" as the branch not existing; rethrow other errors.
      if (!(e instanceof APIError && e.status === 404)) {
        throw e;
      }
    }

    if (!branchExists) {
      // Create the branch from the default branch
      await this.createBranch(branch, this.branch);
    }

    // Persist files to the branch
    const operations = await this.getChangeFileOperations(files, branch);
    await this.changeFiles(operations, branch, options);

    if (!branchExists) {
      const pr = await this.createPR(options.commitMessage, branch);
      const status = options.status || this.initialWorkflowStatus;
      await this.setPullRequestStatus(pr, status);
    }
  }
}
