import { Base64 } from 'js-base64';
import trimStart from 'lodash/trimStart';
import trim from 'lodash/trim';
import result from 'lodash/result';
import partial from 'lodash/partial';
import last from 'lodash/last';
import initial from 'lodash/initial';
import {
  APIError,
  basename,
  generateContentKey,
  getAllResponses,
  localForage,
  parseContentKey,
  readFileMetadata,
  requestWithBackoff,
  unsentRequest,
  CMS_BRANCH_PREFIX,
  branchFromContentKey,
  isCMSLabel,
  labelToStatus,
  statusToLabel,
  DEFAULT_PR_BODY,
  MERGE_COMMIT_MESSAGE,
} from 'decap-cms-lib-util';

import type {
  DataFile,
  PersistOptions,
  AssetProxy,
  ApiRequest,
  FetchError,
} from 'decap-cms-lib-util';
import type { Semaphore } from 'semaphore';
import type {
  FilesResponse,
  GitGetBlobResponse,
  GitGetTreeResponse,
  GiteaUser,
  GiteaRepository,
  ReposListCommitsResponse,
  GiteaPullRequest,
  GiteaBranch,
  GiteaLabel,
  GiteaChangedFile,
} from './types';

export const API_NAME = 'Gitea';

export interface Config {
  apiRoot?: string;
  token?: string;
  branch?: string;
  repo?: string;
  originRepo?: string;
  useOpenAuthoring?: boolean;
}

enum FileOperation {
  CREATE = 'create',
  DELETE = 'delete',
  UPDATE = 'update',
}

export interface ChangeFileOperation {
  content?: string;
  from_path?: string;
  path: string;
  operation: FileOperation;
  sha?: string;
}

interface MetaDataObjects {
  entry: { path: string; sha: string };
  files: MediaFile[];
}

export interface Metadata {
  type: string;
  objects: MetaDataObjects;
  branch: string;
  status: string;
  collection: string;
  commitMessage: string;
  version?: string;
  user: string;
  title?: string;
  description?: string;
  timeStamp: string;
}

export interface BlobArgs {
  sha: string;
  repoURL: string;
  parseText: boolean;
}

type Param = string | number | undefined;

export type Options = RequestInit & {
  params?: Record<string, Param | Record<string, Param> | string[]>;
};

type MediaFile = {
  sha: string;
  path: string;
};

export default class API {
  apiRoot: string;
  token: string;
  branch: string;
  repo: string;
  originRepo: string;
  repoOwner: string;
  repoName: string;
  originRepoOwner: string;
  originRepoName: string;
  repoURL: string;
  originRepoURL: string;
  useOpenAuthoring: boolean;

  _userPromise?: Promise<GiteaUser>;
  _metadataSemaphore?: Semaphore;
  _userIsOriginMaintainerPromises?: {
    [key: string]: Promise<boolean>;
  };

  commitAuthor?: {};

  constructor(config: Config) {
    this.apiRoot = config.apiRoot || 'https://try.gitea.io/api/v1';
    this.token = config.token || '';
    this.branch = config.branch || 'master';
    this.repo = config.repo || '';
    this.originRepo = config.originRepo || this.repo;
    this.useOpenAuthoring = config.useOpenAuthoring ? true : false;
    this.repoURL = `/repos/${this.repo}`;
    this.originRepoURL = `/repos/${this.originRepo}`;

    const [repoParts, originRepoParts] = [this.repo.split('/'), this.originRepo.split('/')];
    this.repoOwner = repoParts[0];
    this.repoName = repoParts[1];

    this.originRepoOwner = originRepoParts[0];
    this.originRepoName = originRepoParts[1];
  }

  static DEFAULT_COMMIT_MESSAGE = 'Automatically generated by Static CMS';

  user(): Promise<{ full_name: string; login: string; avatar_url: string }> {
    if (!this._userPromise) {
      this._userPromise = this.getUser();
    }
    return this._userPromise;
  }

  getUser() {
    return this.request('/user') as Promise<GiteaUser>;
  }

  async hasWriteAccess() {
    try {
      const result: GiteaRepository = await this.request(this.repoURL);
      // update config repoOwner to avoid case sensitivity issues with Gitea
      this.repoOwner = result.owner.login;
      return result.permissions.push;
    } catch (error) {
      console.error('Problem fetching repo data from Gitea');
      throw error;
    }
  }

  reset() {
    // no op
  }

  requestHeaders(headers = {}) {
    const baseHeader: Record<string, string> = {
      'Content-Type': 'application/json; charset=utf-8',
      ...headers,
    };

    if (this.token) {
      baseHeader.Authorization = `token ${this.token}`;
      return Promise.resolve(baseHeader);
    }

    return Promise.resolve(baseHeader);
  }

  async parseJsonResponse(response: Response) {
    const json = await response.json();
    if (!response.ok) {
      return Promise.reject(json);
    }
    return json;
  }

  urlFor(path: string, options: Options) {
    const params = [];
    if (options.params) {
      for (const key in options.params) {
        params.push(`${key}=${encodeURIComponent(options.params[key] as string)}`);
      }
    }
    if (params.length) {
      path += `?${params.join('&')}`;
    }
    return this.apiRoot + path;
  }

  parseResponse(response: Response) {
    const contentType = response.headers.get('Content-Type');
    if (contentType && contentType.match(/json/)) {
      return this.parseJsonResponse(response);
    }
    const textPromise = response.text().then(text => {
      if (!response.ok) {
        return Promise.reject(text);
      }
      return text;
    });
    return textPromise;
  }

  handleRequestError(error: FetchError, responseStatus: number) {
    throw new APIError(error.message, responseStatus, API_NAME);
  }

  buildRequest(req: ApiRequest) {
    return req;
  }

  async request(
    path: string,
    options: Options = {},
    parser = (response: Response) => this.parseResponse(response),
  ) {
    options = { cache: 'no-cache', ...options };
    const headers = await this.requestHeaders(options.headers || {});
    const url = this.urlFor(path, options);
    let responseStatus = 500;

    try {
      const req = unsentRequest.fromFetchArguments(url, {
        ...options,
        headers,
      }) as unknown as ApiRequest;
      const response = await requestWithBackoff(this, req);
      responseStatus = response.status;
      const parsedResponse = await parser(response);
      return parsedResponse;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (error: any) {
      return this.handleRequestError(error, responseStatus);
    }
  }

  nextUrlProcessor() {
    return (url: string) => url;
  }

  async requestAllPages<T>(url: string, options: Options = {}) {
    options = { cache: 'no-cache', ...options };
    const headers = await this.requestHeaders(options.headers || {});
    const processedURL = this.urlFor(url, options);
    const allResponses = await getAllResponses(
      processedURL,
      { ...options, headers },
      'next',
      this.nextUrlProcessor(),
    );
    const pages: T[][] = await Promise.all(
      allResponses.map((res: Response) => this.parseResponse(res)),
    );
    return ([] as T[]).concat(...pages);
  }

  generateContentKey(collectionName: string, slug: string) {
    return generateContentKey(collectionName, slug);
  }

  parseContentKey(contentKey: string) {
    return parseContentKey(contentKey);
  }

  async readFile(
    path: string,
    sha?: string | null,
    {
      branch = this.branch,
      repoURL = this.repoURL,
      parseText = true,
    }: {
      branch?: string;
      repoURL?: string;
      parseText?: boolean;
    } = {},
  ) {
    if (!sha) {
      sha = await this.getFileSha(path, { repoURL, branch });
    }
    const content = await this.fetchBlobContent({ sha: sha as string, repoURL, parseText });
    return content;
  }

  async readFileMetadata(path: string, sha: string | null | undefined) {
    const fetchFileMetadata = async () => {
      try {
        const result: ReposListCommitsResponse = await this.request(
          `${this.originRepoURL}/commits`,
          {
            params: { path, sha: this.branch, stat: 'false' },
          },
        );
        const { commit } = result[0];
        return {
          author: commit.author.name || commit.author.email,
          updatedOn: commit.author.date,
        };
      } catch (e) {
        return { author: '', updatedOn: '' };
      }
    };
    const fileMetadata = await readFileMetadata(sha, fetchFileMetadata, localForage);
    return fileMetadata;
  }

  async fetchBlobContent({ sha, repoURL, parseText }: BlobArgs) {
    const result: GitGetBlobResponse = await this.request(`${repoURL}/git/blobs/${sha}`, {
      cache: 'force-cache',
    });

    if (parseText) {
      // treat content as a utf-8 string
      const content = Base64.decode(result.content);
      return content;
    } else {
      // treat content as binary and convert to blob
      const content = Base64.atob(result.content);
      const byteArray = new Uint8Array(content.length);
      for (let i = 0; i < content.length; i++) {
        byteArray[i] = content.charCodeAt(i);
      }
      const blob = new Blob([byteArray]);
      return blob;
    }
  }

  async listFiles(
    path: string,
    { repoURL = this.repoURL, branch = this.branch, depth = 1 } = {},
    folderSupport?: boolean,
  ): Promise<{ type: string; id: string; name: string; path: string; size: number }[]> {
    const folder = trim(path, '/');
    try {
      const result: GitGetTreeResponse = await this.request(
        `${repoURL}/git/trees/${branch}:${encodeURIComponent(folder)}`,
        {
          // Gitea API supports recursive=1 for getting the entire recursive tree
          // or omitting it to get the non-recursive tree
          params: depth > 1 ? { recursive: 1 } : {},
        },
      );
      return (
        result.tree
          // filter only files and/or folders up to the required depth
          .filter(
            file =>
              (!folderSupport ? file.type === 'blob' : true) &&
              decodeURIComponent(file.path).split('/').length <= depth,
          )
          .map(file => ({
            type: file.type,
            id: file.sha,
            name: basename(file.path),
            path: `${folder}/${file.path}`,
            size: file.size!,
          }))
      );
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      if (err && err.status === 404) {
        console.info('[StaticCMS] This 404 was expected and handled appropriately.');
        return [];
      } else {
        throw err;
      }
    }
  }

  async persistFiles(dataFiles: DataFile[], mediaFiles: AssetProxy[], options: PersistOptions) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const files: (DataFile | AssetProxy)[] = mediaFiles.concat(dataFiles as any);
    const operations = await this.getChangeFileOperations(files, this.branch);
    return this.changeFiles(operations, options);
  }

  async changeFiles(operations: ChangeFileOperation[], options: PersistOptions) {
    return (await this.request(`${this.repoURL}/contents`, {
      method: 'POST',
      body: JSON.stringify({
        branch: this.branch,
        files: operations,
        message: options.commitMessage,
      }),
    })) as FilesResponse;
  }

  async getChangeFileOperations(files: { path: string; newPath?: string }[], branch: string) {
    const items: ChangeFileOperation[] = await Promise.all(
      files.map(async file => {
        const content = await result(
          file,
          'toBase64',
          partial(this.toBase64, (file as DataFile).raw),
        );
        let sha;
        let operation;
        let from_path;
        let path = trimStart(file.path, '/');
        try {
          sha = await this.getFileSha(file.path, { branch });
          operation = FileOperation.UPDATE;
          from_path = file.newPath && path;
          path = file.newPath ? trimStart(file.newPath, '/') : path;
        } catch {
          sha = undefined;
          operation = FileOperation.CREATE;
        }

        return {
          operation,
          content,
          path,
          from_path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    return items;
  }

  async getFileSha(path: string, { repoURL = this.repoURL, branch = this.branch } = {}) {
    /**
     * We need to request the tree first to get the SHA. We use extended SHA-1
     * syntax (<rev>:<path>) to get a blob from a tree without having to recurse
     * through the tree.
     */

    const pathArray = path.split('/');
    const filename = last(pathArray);
    const directory = initial(pathArray).join('/');
    const fileDataPath = encodeURIComponent(directory);
    const fileDataURL = `${repoURL}/git/trees/${branch}:${fileDataPath}`;

    const result: GitGetTreeResponse = await this.request(fileDataURL);
    const file = result.tree.find(file => file.path === filename);
    if (file) {
      return file.sha;
    } else {
      throw new APIError('Not Found', 404, API_NAME);
    }
  }

  async deleteFiles(paths: string[], message: string) {
    const operations: ChangeFileOperation[] = await Promise.all(
      paths.map(async path => {
        const sha = await this.getFileSha(path);

        return {
          operation: FileOperation.DELETE,
          path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    this.changeFiles(operations, { commitMessage: message });
  }

  toBase64(str: string) {
    return Promise.resolve(Base64.encode(str));
  }

  async getBranch(branchName: string): Promise<GiteaBranch> {
    return this.request(`${this.repoURL}/branches/${encodeURIComponent(branchName)}`);
  }

  async getDefaultBranch(): Promise<GiteaBranch> {
    return this.getBranch(this.branch);
  }

  async createBranch(
    branchName: string,
    oldBranchName: string = this.branch,
  ): Promise<GiteaBranch> {
    return this.request(`${this.repoURL}/branches`, {
      method: 'POST',
      body: JSON.stringify({
        new_branch_name: branchName,
        old_ref_name: oldBranchName,
      }),
    });
  }

  async deleteBranch(branchName: string): Promise<void> {
    await this.request(`${this.repoURL}/branches/${encodeURIComponent(branchName)}`, {
      method: 'DELETE',
    });
  }

  async getPullRequests(
    state: 'open' | 'closed' | 'all' = 'open',
    head?: string,
  ): Promise<GiteaPullRequest[]> {
    const params: Record<string, string> = { state };
    if (head) {
      params.head = head;
    }
    return this.request(`${this.originRepoURL}/pulls`, { params });
  }

  async getOpenAuthoringPullRequest(branch: string, pullRequests: GiteaPullRequest[]) {
    // we can't use labels when using open authoring
    // since the contributor doesn't have access to set labels
    // a branch without a pr (or a closed pr) means a 'draft' entry
    // a branch with an opened pr means a 'pending_review' entry
    const data = await this.getBranch(branch).catch(() => {
      throw new APIError('content is not under editorial workflow', 400, API_NAME);
    });
    // since we get all (open and closed) pull requests by branch name, make sure to filter by head sha
    const pullRequest = pullRequests.filter(pr => pr.head.sha === data.commit.id)[0];
    // if no pull request is found for the branch we return a mocked one
    if (!pullRequest) {
      try {
        return {
          id: -1,
          number: -1,
          state: 'open' as const,
          title: 'Draft',
          body: '',
          user: { login: 'unknown' } as GiteaUser,
          labels: [],
          head: { sha: data.commit.id, ref: branch, label: branch, repo: {} as GiteaRepository },
          base: { sha: '', ref: '', label: '', repo: {} as GiteaRepository },
          merged: false,
          merged_at: null,
          updated_at: new Date().toISOString(),
          created_at: new Date().toISOString(),
        } as GiteaPullRequest;
      } catch (e) {
        throw new APIError('content is not under editorial workflow', 400, API_NAME);
      }
    } else {
      // Filter out CMS labels for open authoring
      const cmsLabelPrefix = 'decap-cms/';
      pullRequest.labels = pullRequest.labels.filter(l => !isCMSLabel(l.name, cmsLabelPrefix));
      return pullRequest;
    }
  }

  async getBranchPullRequest(branchName: string): Promise<GiteaPullRequest> {
    const pullRequests = await this.getPullRequests('open', `${this.repoOwner}:${branchName}`);
    if (pullRequests.length > 0) {
      return pullRequests[0];
    }
    // Check closed PRs as fallback
    const closedPRs = await this.getPullRequests('closed', `${this.repoOwner}:${branchName}`);
    if (closedPRs.length > 0) {
      return closedPRs[0];
    }
    throw new APIError('Pull request not found', 404, API_NAME);
  }

  async createPR(
    title: string,
    head: string,
    body: string = DEFAULT_PR_BODY,
  ): Promise<GiteaPullRequest> {
    return this.request(`${this.originRepoURL}/pulls`, {
      method: 'POST',
      body: JSON.stringify({
        title,
        head,
        base: this.branch,
        body,
      }),
    });
  }

  async updatePR(number: number, state: 'open' | 'closed'): Promise<GiteaPullRequest> {
    return this.request(`${this.originRepoURL}/pulls/${number}`, {
      method: 'PATCH',
      body: JSON.stringify({ state }),
    });
  }

  async closePR(number: number): Promise<GiteaPullRequest> {
    return this.updatePR(number, 'closed');
  }

  async mergePR(pullRequest: GiteaPullRequest): Promise<void> {
    await this.request(`${this.originRepoURL}/pulls/${pullRequest.number}/merge`, {
      method: 'POST',
      body: JSON.stringify({
        do: 'merge',
        merge_message_field: MERGE_COMMIT_MESSAGE,
      }),
    });
  }

  async getPullRequestFiles(number: number): Promise<GiteaChangedFile[]> {
    return this.request(`${this.originRepoURL}/pulls/${number}/files`);
  }

  async updatePullRequestLabels(number: number, labels: number[]): Promise<GiteaLabel[]> {
    return this.request(`${this.originRepoURL}/issues/${number}/labels`, {
      method: 'PUT',
      body: JSON.stringify({ labels }),
    });
  }

  async getLabels(): Promise<GiteaLabel[]> {
    return this.request(`${this.originRepoURL}/labels`);
  }

  async createLabel(name: string, color = '0052cc'): Promise<GiteaLabel> {
    return this.request(`${this.originRepoURL}/labels`, {
      method: 'POST',
      body: JSON.stringify({ name, color }),
    });
  }

  async getOrCreateLabel(name: string): Promise<GiteaLabel> {
    const labels = await this.getLabels();
    const existing = labels.find(l => l.name === name);
    if (existing) {
      return existing;
    }
    return this.createLabel(name);
  }

  async setPullRequestStatus(pullRequest: GiteaPullRequest, status: string): Promise<void> {
    // Skip label updates for open authoring as contributors don't have permission
    if (this.useOpenAuthoring) {
      return;
    }

    const cmsLabelPrefix = 'decap-cms/';
    const newLabel = statusToLabel(status, cmsLabelPrefix);

    // Get or create the new status label
    const label = await this.getOrCreateLabel(newLabel);

    // Get current labels and filter out old CMS labels
    const currentLabels = pullRequest.labels
      .filter(l => !isCMSLabel(l.name, cmsLabelPrefix))
      .map(l => l.id);

    // Add the new status label
    await this.updatePullRequestLabels(pullRequest.number, [...currentLabels, label.id]);
  }

  async listUnpublishedBranches(): Promise<string[]> {
    const pullRequests = await this.getPullRequests('open');
    const cmsBranches = pullRequests
      .filter(pr => pr.head.ref.startsWith(`${CMS_BRANCH_PREFIX}/`))
      .map(pr => pr.head.ref);

    return cmsBranches;
  }

  async retrieveUnpublishedEntryData(contentKey: string) {
    const branch = branchFromContentKey(contentKey);
    let pullRequest: GiteaPullRequest;

    if (this.useOpenAuthoring) {
      const pullRequests = await this.getPullRequests('all');
      pullRequest = await this.getOpenAuthoringPullRequest(branch, pullRequests);
    } else {
      pullRequest = await this.getBranchPullRequest(branch);
    }

    const files = await this.getPullRequestFiles(pullRequest.number);

    const cmsLabelPrefix = 'decap-cms/';
    let status = 'draft';

    if (this.useOpenAuthoring) {
      // For open authoring, status is based on PR state, not labels
      status = pullRequest.state === 'open' ? 'pending_review' : 'draft';
    } else {
      const statusLabel = pullRequest.labels.find(l => isCMSLabel(l.name, cmsLabelPrefix));
      status = statusLabel ? labelToStatus(statusLabel.name, cmsLabelPrefix) : 'draft';
    }

    const { collection, slug } = this.parseContentKey(contentKey);

    return {
      collection,
      slug,
      status,
      diffs: files.map(file => ({
        path: file.filename,
        newFile: file.status === 'added',
        id: '', // SHA not directly available from files endpoint
      })),
      updatedAt: pullRequest.updated_at,
      pullRequestAuthor: pullRequest.user?.login || 'Unknown',
    };
  }

  async updateUnpublishedEntryStatus(collection: string, slug: string, newStatus: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);
    const pullRequest = await this.getBranchPullRequest(branch);
    await this.setPullRequestStatus(pullRequest, newStatus);
  }

  async deleteUnpublishedEntry(collection: string, slug: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    try {
      const pullRequest = await this.getBranchPullRequest(branch);
      await this.closePR(pullRequest.number);
    } catch (e) {
      // PR might not exist, continue to delete branch
    }

    await this.deleteBranch(branch);
  }

  async publishUnpublishedEntry(collection: string, slug: string) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    const pullRequest = await this.getBranchPullRequest(branch);
    await this.mergePR(pullRequest);
    await this.deleteBranch(branch);
  }

  async editorialWorkflowGit(
    files: { path: string; newPath?: string }[],
    slug: string,
    collection: string,
    options: PersistOptions,
  ) {
    const contentKey = this.generateContentKey(collection, slug);
    const branch = branchFromContentKey(contentKey);

    let branchExists = false;
    try {
      await this.getBranch(branch);
      branchExists = true;
    } catch (e) {
      // Branch doesn't exist
    }

    if (!branchExists) {
      // Create the branch from the default branch
      await this.createBranch(branch, this.branch);
    }

    // Persist files to the branch
    const operations = await this.getChangeFileOperationsForBranch(files, branch);
    await this.changeFilesOnBranch(operations, options, branch);

    // Create PR if it doesn't exist
    if (!branchExists) {
      const pr = await this.createPR(options.commitMessage, branch);
      // Set initial status
      const status = options.status || 'draft';
      await this.setPullRequestStatus(pr, status);
    }
  }

  async getChangeFileOperationsForBranch(
    files: { path: string; newPath?: string }[],
    branch: string,
  ) {
    const items: ChangeFileOperation[] = await Promise.all(
      files.map(async file => {
        const content = await result(
          file,
          'toBase64',
          partial(this.toBase64, (file as DataFile).raw),
        );
        let sha;
        let operation;
        let from_path;
        let path = trimStart(file.path, '/');
        try {
          sha = await this.getFileSha(file.path, { branch });
          operation = FileOperation.UPDATE;
          from_path = file.newPath && path;
          path = file.newPath ? trimStart(file.newPath, '/') : path;
        } catch {
          sha = undefined;
          operation = FileOperation.CREATE;
        }

        return {
          operation,
          content,
          path,
          from_path,
          sha,
        } as ChangeFileOperation;
      }),
    );
    return items;
  }

  async changeFilesOnBranch(
    operations: ChangeFileOperation[],
    options: PersistOptions,
    branch: string,
  ) {
    return (await this.request(`${this.repoURL}/contents`, {
      method: 'POST',
      body: JSON.stringify({
        branch,
        files: operations,
        message: options.commitMessage,
      }),
    })) as FilesResponse;
  }

  // Open Authoring (Fork) Support
  async forkExists(): Promise<boolean> {
    try {
      const repoName = this.originRepo.split('/')[1];
      const userRepoPath = `/repos/${this.repoOwner}/${repoName}`;
      const repo = (await this.request(userRepoPath)) as GiteaRepository;

      // Check if it's a fork and the parent is the origin repo
      const forkExists: boolean =
        repo.fork === true &&
        !!repo.parent &&
        repo.parent.full_name.toLowerCase() === this.originRepo.toLowerCase();
      return forkExists;
    } catch {
      return false;
    }
  }

  async createFork(): Promise<GiteaRepository> {
    return this.request(`${this.originRepoURL}/forks`, {
      method: 'POST',
    }) as Promise<GiteaRepository>;
  }

  async mergeUpstream(): Promise<void> {
    // Sync fork with upstream repository using Gitea's sync_fork endpoint
    // Available in Gitea 1.17+
    try {
      await this.request(`${this.repoURL}/sync_fork`, {
        method: 'POST',
      });
    } catch (error) {
      // If sync fails (e.g., on older Gitea versions or conflicts),
      // continue without syncing - user will need to sync manually
      console.warn('Failed to sync fork with upstream:', error);
    }
  }
}
