local_backend: true

backend:
  name: git-gateway
  branch: main
  squash_merges: true

logo_url: /media/brand/logo.svg
media_folder: static/media/uploads
public_folder: /media/uploads

slug:
  encoding: ascii
  clean_accents: true

aliases:
  - &VISIBLE_IN_CMS {name: visibleInCMS, widget: hidden, default: true, i18n: duplicate}

collections:
  - name: other
    label: Other
    label_singular: page
    format: yaml-frontmatter
    folder: content
    create: true
    filter: {field: visibleInCMS, value: true}
    editor:
      preview: false
    fields: [
      {name: title, label: Title, widget: string},
      # {name: body, label: Body, widget: richtext},
      {name: body, label: Body, widget: markdown},
      *VISIBLE_IN_CMS,
    ]
