import BaseError from './BaseError';

/**
 * Generic error generated by any HTTP API call. This can include backends or other 3rd party APIs.
 */
export default class APIError extends BaseError {
  /**
   * 
   * @param {string} message error message 
   * @param {number} status http status code for request
   * @param {string} api name of the API within the context of netlify-cms.
   */
  constructor(message, status, api) {
    super(message);
    this.status = status;
    this.api = api;
  }
}
