name: Label PR
on:
  pull_request:
    types: [opened, edited]

jobs:
  label-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'fix')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: bug'
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'chore')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: chore'
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'feat')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: feature'
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'security')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: security'
