name: Generate Sponsors README
on:
  push:
    branches: [ readme-sponsors ]
  workflow_dispatch:
  schedule:
    - cron: 13 13 * * *
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'README.md'

      # ⚠️ Note: You can use any deployment step here to automatically push the README
      # changes back to your branch.
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: readme-sponsors
          folder: '.'